# fly.toml app configuration file generated for mehto-dev on 2024-02-20T20:43:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mehto-dev'
primary_region = 'arn'

[build]
  [build.args]
    GO_VERSION = '1.22.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
